services:
  - type: web
    name: confess-api  # You can name it anything
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker server:app
    envVars:
      - key: FIREBASE_CREDENTIALS
        value: '{{ FIREBASE_CREDENTIALS_JSON }}'
