services:
  - type: web
    name: confess-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server.Routes:app --host 0.0.0.0 --port 10000
    envVars:
      - key: FIREBASE_CREDENTIALS
        value: '{{ FIREBASE_CREDENTIALS_JSON }}'
