services:
  - type: web
    name: FastAPI  # consider renaming to reflect FastAPI
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker server:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: confess-f706a-firebase-adminsdk-fbsvc-64580a51d4.json
